<a href="https://colab.research.google.com/github/Ozeiassantos/Bootscamp_Data_science/blob/main/Gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First **colab** Tensores


**sintaxe Básica do Pytorch**

In [6]:
import torch

lista =[[1,2,3],
        [4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


**Outras formas é apartir de arrays Numby**

In [11]:
import numpy as np

arr = np.random.rand(3,4)
#arr = arr.astype(int)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

print(tns)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
int64


**Tensores Inicialisados**

In [13]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 1.9788,  0.5399, -0.7756],
        [ 0.4896, -0.5394,  0.0544],
        [ 0.8611, -0.7709, -1.2770]])


**Tensor para array Numby**

In [16]:
print(type(tnsr))

arrr = tnsr.data.numpy()
print(arrr)
print(type(arrr))

<class 'torch.Tensor'>
[[ 1.9788213   0.53985983 -0.77560663]
 [ 0.4895604  -0.5393635   0.05441441]
 [ 0.8611105  -0.770947   -1.2770303 ]]
<class 'numpy.ndarray'>


# **Indexação**

In [27]:
print(tnsr)
#tnsr[0, 2] = -10

print('')
print(tnsr)



tensor([[  1.9788,   0.5399, -10.0000],
        [  0.4896,  -0.5394,   0.0544],
        [  0.8611,  -0.7709,  -1.2770]])

tensor([[  1.9788,   0.5399, -10.0000],
        [  0.4896,  -0.5394,   0.0544],
        [  0.8611,  -0.7709,  -1.2770]])


acessando as linhas:

In [30]:
print(tnsr[0:2])
print('')
print(tnsr[:,2])

tensor([[  1.9788,   0.5399, -10.0000],
        [  0.4896,  -0.5394,   0.0544]])

tensor([-10.0000,   0.0544,  -1.2770])


# Operações com tensores

In [37]:
print(tnsr.shape)
print(tns1.shape)

tns = tnsr[0:2,:]
print(tns.shape)
print('')

print(tns)
print('')
print(tns1)
print('')

print(tns + tns1)

print('')

print(tns1/tns)

torch.Size([3, 3])
torch.Size([2, 3])
torch.Size([2, 3])

tensor([[  1.9788,   0.5399, -10.0000],
        [  0.4896,  -0.5394,   0.0544]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[ 2.9788,  1.5399, -9.0000],
        [ 1.4896,  0.4606,  1.0544]])

tensor([[ 0.5054,  1.8523, -0.1000],
        [ 2.0426, -1.8540, 18.3775]])


# Função .size() e .view()

In [44]:
tns2 = torch.randn(2,2,3)
print(tns2)

print(tns2.size())
print('')

tnsv = print(tns2.view(-1))
print(tnsv)

tensor([[[ 1.1024, -0.4721,  0.1864],
         [ 0.8573,  0.6950,  1.4561]],

        [[-0.3974,  0.7795, -0.3172],
         [-0.8229,  0.7513, -0.1204]]])
torch.Size([2, 2, 3])

tensor([ 1.1024, -0.4721,  0.1864,  0.8573,  0.6950,  1.4561, -0.3974,  0.7795,
        -0.3172, -0.8229,  0.7513, -0.1204])
None


### GPU Cast

In [1]:
import torch

tns3 = torch.randn(10)

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tns3 = tns3.to(device)
print(tns3)

cuda
tensor([-0.2637, -0.3690,  1.4339, -0.9729,  0.3255, -0.5697,  0.1105, -0.2718,
        -0.0371,  0.7604], device='cuda:0')
